name: certbot

services:
  certbot:
    build: .
    container_name: certbot
    environment:
      - SUBDOMAIN=${SUBDOMAIN}
      - DUCKDNS_TOKEN=${TOKEN}
    volumes:
      - ../certs:/etc/letsencrypt
volumes:
  certbot-etc:
  certbot-var:
  webroot:
