name: certbot

services:
  certbot:
    build: .
    container_name: certbot
    environment:
      - SUBDOMAIN=lpoplawska
      - DUCKDNS_TOKEN=0bb0ed28-ab3a-47d4-abe6-fe39c049f88e
    volumes:
      - ../certs:/etc/letsencrypt
volumes:
  certbot-etc:
  certbot-var:
  webroot:
