spring.application.name=Infrastructure3Project

spring.datasource.url=jdbc:postgresql://localhost:5432/game
spring.datasource.username=spring
spring.datasource.password=spring

spring.sql.init.mode=always
spring.jpa.generate-ddl=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view= false

server.forward-headers-strategy=framework
server.servlet.context-path=/app1
